### ISSUE TITLE
Include more complete usage guide in Readme

### ISSUE THREAD

**Issue by bdemers** [retrostreams/android-retrostreams#4]
The usage of this project (and Android's desugar/d8 toolchain) is a little light.

How would I configure D8 to use this library.  I'm guessing I need to configure byte code translation to rewrite package names, but i'm not sure where that is configured.

Are there example projects?

**Comment by stefan-zobel** [comment]
The Android Studio configuration doesn't differ from any other project that has dependencies which use Java 8 language features.
In your `build.gradle` you set 

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

and `minSdkVersion` to, say, `15` and you're ready to go.

You seem to believe that `android-retrostreams` makes it possible to use the Java 8 package names `java.util.stream`, `java.util.function`, ... in your code.
That's a misconception. You have to use the corresponding retrostreams [API](http://www.javadoc.io/doc/net.sourceforge.streamsupport/android-retrostreams/1.7.0) that lives in `java9.util.stream`, `java9.util.function` and so on.

To create a j9.u.s.Stream from a java.util.Collection you basically use the static j9.u.s.StreamSupport methods [stream(Collection)](http://static.javadoc.io/net.sourceforge.streamsupport/android-retrostreams/1.7.0/java9/util/stream/StreamSupport.html#stream-java.util.Collection-), or (for a parallel Stream) [parallelStream(Collection)](http://static.javadoc.io/net.sourceforge.streamsupport/android-retrostreams/1.7.0/java9/util/stream/StreamSupport.html#parallelStream-java.util.Collection-).
That's the essential difference from how you'd obtain a Stream in Java 8. Once you have an instance of a j9.u.s.Stream its usage and behavior is virtually indistinguishable from a standard Java stream. However, you are bound to import the `java9` packages instead of the standard ones.

If you happen to have a binary dependency which uses the standard Stream API internally there's another route you could try: **_ProGuard 6.1_** has a new feature that allows you to rewrite that bytecode to use the [streamsupport](https://github.com/stefan-zobel/streamsupport) implementation instead.
See https://sourceforge.net/p/proguard/discussion/182455/thread/04f596f59f/ or https://github.com/stefan-zobel/streamsupport/issues/5 (I'm not affiliated or familiar with this approach, however)

HTH,
Stefan

**Comment by bdemers** [comment]
Thanks for the clarification @stefan-zobel, I guess i was just confused by the repo description:
> Backport of Java 9 java.util.stream API for Android Studio 3.0 desugar toolchain

Which seems to imply bytecode manipulation switching out the jdk streams to this project.

**Comment by stefan-zobel** [comment]
The value added by desugar / D8 is that you can now have _default_ and _static_ interface methods in a library jar like android-retrostreams and use them from your project without having to include the library sources.

That was not possible with Jack and awkward (to say the least) with retrolambda. That's where the "... for Android Studio 3.0 desugar toolchain ..." came from.
